services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: a
    ports:
      - '27017:27017'
    volumes:
      - mongo_nest:/data/db
volumes:
  mongo_nest:
